//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroSpy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroSpy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;analog&apos; needs attribute &apos;direction&apos;..
        /// </summary>
        internal static string AnalogNeedsDirection {
            get {
                return ResourceManager.GetString("AnalogNeedsDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;background&apos; should either define &apos;image&apos; with optionally &apos;width&apos; and &apos;height&apos; or both &apos;width&apos; and &apos;height&apos;..
        /// </summary>
        internal static string BothWidthAndHeight {
            get {
                return ResourceManager.GetString("BothWidthAndHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GamepadReader could not find a connected gamepad with the given id..
        /// </summary>
        internal static string CouldNotConnectToGamePad {
            get {
                return ResourceManager.GetString("CouldNotConnectToGamePad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangebutton &apos;from&apos; field cannot be greater than &apos;to&apos; field..
        /// </summary>
        internal static string FromCannotBeGreaterThanTo {
            get {
                return ResourceManager.GetString("FromCannotBeGreaterThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected gamepad could not be acquired..
        /// </summary>
        internal static string GamepadCouldNotBeAcquired {
            get {
                return ResourceManager.GetString("GamepadCouldNotBeAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;analog&apos; attribute &apos;direction&apos; has illegal value. Valid values are &apos;up&apos;, &apos;down&apos;, &apos;left&apos;, &apos;right&apos;, &apos;fade&apos;..
        /// </summary>
        internal static string IllegalDirection {
            get {
                return ResourceManager.GetString("IllegalDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal value specified for skin attribute &apos;type&apos;..
        /// </summary>
        internal static string IllegalSkinType {
            get {
                return ResourceManager.GetString("IllegalSkinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected keyboard could not be acquired..
        /// </summary>
        internal static string KeyboardCouldNotBeAcquired {
            get {
                return ResourceManager.GetString("KeyboardCouldNotBeAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected mouse could not be acquired..
        /// </summary>
        internal static string MouseCouldNotBeAcquired {
            get {
                return ResourceManager.GetString("MouseCouldNotBeAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin must contain at least one background..
        /// </summary>
        internal static string OneBackground {
            get {
                return ResourceManager.GetString("OneBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder..
        /// </summary>
        internal static string PleaseSelectAFolder {
            get {
                return ResourceManager.GetString("PleaseSelectAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG file (*.png)|*.png.
        /// </summary>
        internal static string PNGFilter {
            get {
                return ResourceManager.GetString("PNGFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port 1 and Port 2 cannot be the same!.
        /// </summary>
        internal static string Port1And2CannotBeTheSame {
            get {
                return ResourceManager.GetString("Port1And2CannotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetroSpy.
        /// </summary>
        internal static string RetroSpy {
            get {
                return ResourceManager.GetString("RetroSpy", resourceCulture);
            }
        }
    }
}
